export const LOAD_CONTACTS = 'LOAD_CONTACTS';
export const ADD_FAVORITE_CONTACT = 'ADD_FAVORITE_CONTACT';
export const REMOVE_FAVORITE_CONTACT = 'REMOVE_FAVORITE_CONTACT';
export const UPDATE_CURRENT_CONTACT = 'UPDATE_CURRENT_CONTACT';
